version: '3.8'

services:
  user-gateway:
    container_name: user-gateway
    restart: always
    build:
      dockerfile: ../user-gateway/Dockerfile
      context: ../user-gateway
    image: hiimtuan/user-gateway
    ports:
      - '3000:3000'
    networks:
      - docker_gotrek
    volumes: 
      - ../user-gateway/.env:/go/src/app/.env
    env_file: 
      - ../user-gateway/.env

networks:
  docker_gotrek:
    external: true